/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restclient.managementhotel;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Kamar extends javax.swing.JFrame {

    /**
     * Creates new form Kamar
     */
    public Kamar() {
        initComponents();
        loadTabelKamar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblKamar = new javax.swing.JTable();
        txtCari = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblKamar);

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        btnTambah.setText("Tambah Data");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit Data");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus Data");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(btnTambah)
                        .addGap(137, 137, 137)
                        .addComponent(btnHapus)
                        .addGap(165, 165, 165)
                        .addComponent(btnEdit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnHapus)
                    .addComponent(btnEdit))
                .addGap(87, 87, 87))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
Connection conn = Koneksi.connectDB();

    /**
     *
     * @throws SQLException
     * @throws com.restclient.managementhotel.SQLException
     * @throws com.restclient.managementhotel.SQLException
     */
    public void loadTabelKamar(){

        String sql = "SELECT * FROM kamar";
        Object[] kolom = {"No", "Nomor Kamar", "Tipe Tempat Tidur",
            "Tipe Kamar", "Status","Harga (Rupiah)"};
        DefaultTableModel dataModel = new DefaultTableModel(null, kolom);
        tblKamar.setModel(dataModel);
        tblKamar.getColumnModel().getColumn(0).setMaxWidth(30);
        
        try{
            Statement stmt = conn.createStatement();
            ResultSet rs   = stmt.executeQuery(sql);
            
            while(rs.next()){    
                int id = rs.getInt("id_kamar");
                String no = rs.getString("no_kamar");
                String ttt = rs.getString("tipe_bed");
                String t_kamar = rs.getString("tipe_kamar");
                String status = rs.getString("occupied");
                int harga = rs.getInt("harga");
                String hrg = "Rp. " + printDigits(harga);
                Object[] data={id, no, ttt, t_kamar, status, hrg};
                dataModel.addRow(data);
            }
        } catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    
   public String printDigits(int nilai) {
    return NumberFormat.getNumberInstance(Locale.US).format(nilai);
    }
        public void loadTabelKamar(String teks) throws SQLException{
        Connection conn = Koneksi.connectDB();
        String sql = "SELECT * FROM kamar WHERE no_kamar like '%"+ teks +"%'";
        Object[] kolom = {"No", "Nomor Kamar", "Tipe Tempat Tidur",
            "Tipe Kamar", "Status","Harga"};
        DefaultTableModel dataModel = new DefaultTableModel(null, kolom);
        tblKamar.setModel(dataModel);
        tblKamar.getColumnModel().getColumn(0).setMaxWidth(30);
        
        try{
            Statement stmt = conn.createStatement();
           ResultSet rs   = stmt.executeQuery(sql);
            
            while(rs.next()){
                int id = rs.getInt("id_kamar");
                String no = rs.getString("no_kamar");
                String ttt = rs.getString("tipe_bed");
                String t_kamar = rs.getString("tipe_kamar");
                String status = rs.getString("occupied");
                int harga = rs.getInt("harga");
                
                Object[] data={id, no, ttt, t_kamar, status, harga};
                dataModel.addRow(data);
            }
        } catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
        
    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        TambahKamar fTK = new TambahKamar();
        fTK.show();
        this.hide();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
         if(tblKamar.isRowSelected(tblKamar.getSelectedRow())==true){
            int selectedID = (int)tblKamar.getValueAt(tblKamar.getSelectedRow(), 0);
            
            int result = JOptionPane.showConfirmDialog(
                this,
                "Kamu akan menghapus data Kamar"
                        + tblKamar.getValueAt(tblKamar.getSelectedRow(),1).toString(),
                "Peringatan!",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );
            
            if (result == JOptionPane.YES_OPTION){
                try{
                    Statement stmt = conn.createStatement();
                    stmt.executeUpdate("DELETE FROM kamar WHERE id_kamar='"
                            + selectedID + "'");
                    loadTabelKamar();
                } catch (SQLException e) {
                    System.out.println(e);
                }
            }
         } else {
             JOptionPane.showMessageDialog(this, "Tidak ada yang dipilih");
         }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        if(tblKamar.isRowSelected(tblKamar.getSelectedRow())==true){
            int selectedID = (int)tblKamar.getValueAt(tblKamar.getSelectedRow(), 0);
            JTextField txtNo = new JTextField(15);
            JTextField txtHarga = new JTextField(15);
            JTextField txtTttidur = new JTextField(15);
            JTextField txtTkamar = new JTextField(15);
            JTextField txtStatus = new JTextField(15);
            
            
            txtNo.setText(tblKamar.getValueAt(tblKamar.getSelectedRow(), 1).toString());
            txtTttidur.setText(tblKamar.getValueAt(tblKamar.getSelectedRow(), 2).toString());
            txtTkamar.setText(tblKamar.getValueAt(tblKamar.getSelectedRow(), 3).toString());
            txtStatus.setText(tblKamar.getValueAt(tblKamar.getSelectedRow(), 4).toString());
            txtHarga.setText(tblKamar.getValueAt(tblKamar.getSelectedRow(), 5).toString());
            
            JPanel myPanel = new JPanel();
            myPanel.add(new JLabel("Nomor Kamar"));
            myPanel.add(txtNo);
            myPanel.add(new JLabel("Tipe Tempat Tidur"));
            myPanel.add(txtTttidur);
            myPanel.add(new JLabel("Tipe Kamar"));
            myPanel.add(txtTkamar);
            myPanel.add(new JLabel("Harga Kamar"));
            myPanel.add(txtHarga);
            
            int result = JOptionPane.showConfirmDialog(this, myPanel,
                "Edit Data", 
                JOptionPane.OK_CANCEL_OPTION,JOptionPane.PLAIN_MESSAGE);
             
            if (result == JOptionPane.OK_OPTION){
                try{
                    Statement stmt = conn.createStatement();
                    stmt.executeUpdate("UPDATE kamar SET no_kamar='"
                        + txtNo.getText()  + "', tipe_bed='"
                        + txtTttidur.getText() +  "', tipe_kamar='"
                        + txtTkamar.getText() + "', harga='"
                        + txtHarga.getText() + "' WHERE id_kamar='"
                        + selectedID + "'");
                    loadTabelKamar();
                } catch (SQLException e) {
                    System.out.println(e.getMessage());
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Tidak ada yang dipilih");
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
                if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            String teks = txtCari.getText();
            try {
                loadTabelKamar(teks);
            } catch (SQLException e) {
                Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_txtCariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kamar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblKamar;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
