/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.restclient.managementhotel;

import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class TambahReservasi extends javax.swing.JFrame {

    /**
     * Creates new form TambahReservasi
     */
    public TambahReservasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNo = new javax.swing.JTextField();
        txtKp = new javax.swing.JTextField();
        txtNp = new javax.swing.JTextField();
        txtNkamar = new javax.swing.JTextField();
        tglCin = new com.toedter.calendar.JDateChooser();
        tglCout = new com.toedter.calendar.JDateChooser();
        txtNr = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nomor");

        jLabel2.setText("Kode Pengunjung");

        jLabel3.setText("Nama Pengunjung");

        jLabel4.setText("No.Kamar");

        jLabel5.setText("Tanggal Check-In");

        jLabel6.setText("Tanggal Check-Out");

        jLabel7.setText("Kode Resepsionis");

        jLabel8.setText("Status Reservasi");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tglCin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tglCout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNr)
                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNkamar)
                    .addComponent(txtNp)
                    .addComponent(txtKp)
                    .addComponent(txtNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addComponent(btnKembali))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNkamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(tglCin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnKembali)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tglCout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
            // TODO add your handling code here:
        Reservasi1 form = null;
        try {
            form = new Reservasi1();
        } catch (SQLException ex) {
            Logger.getLogger(TambahReservasi.class.getName()).log(Level.SEVERE, null, ex);
        }
        form.show();
        this.hide();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed

          try {
      //Menyebabkan xml injection
            String no = txtNo.getText();
            String kp = txtKp.getText();
            String np = txtNp.getText();
            String nk = txtNkamar.getText();
            String nr = txtNr.getText();
            int status = cbStatus.getSelectedIndex();
            if (!Pattern.matches("[[0-9]]+",no)){
                JOptionPane.showMessageDialog(null, "Format Nomor Tidak valid");
            } else if 
                  (!Pattern.matches("[[0-9]]+",nk)){
                JOptionPane.showMessageDialog(null, "Format Nomor Kamar Tidak valid");
            } else if
                    (!Pattern.matches("[A-Za-z0-9_-]+",kp)){
                JOptionPane.showMessageDialog(null, "Format Kode Pengunjung Tidak valid");
            
            } else if
                    (!Pattern.matches("[A-Za-z0-9]+",nr)){
                JOptionPane.showMessageDialog(null, "Format Kode Resepsionis Tidak valid");
            }
            
              else {
                    simpanReservasi();
                    Reservasi1 form = new Reservasi1();
                    form.show();
                    this.hide();
                }
            }
            catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed
    private void simpanReservasi() throws Exception {
            String no = txtNo.getText();
            String kp = txtKp.getText();
            String np = txtNp.getText();
            String nk = txtNkamar.getText();
            String nr = txtNr.getText();
            DateFormat dsF = new SimpleDateFormat("yyyy-MM-dd");
            String tgla = dsF.format(tglCin.getDate());
            String tglb = dsF.format(tglCout.getDate());
            int status = cbStatus.getSelectedIndex();
        try {
            Connection conn = Koneksi.connectDB();     
            String sql = "INSERT INTO reservasi (id_reservasi, kode_customer, "
                    + "no_kamar, tgl_checkin, tgl_checkout, kode_recept, status_reservasi) VALUES "
                    + "('" + no + "', '" + kp+ "','" + nk+ "', '"
                    + tgla+ "', '" + tglb +"', '"+status +"');";
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO reservasi (id_reservasi, kode_customer, "
                    + "no_kamar, tgl_checkin, tgl_checkout, kode_recept, status_reservasi) VALUES (?, ?, ?, ?, ?, ?,?)");
            stmt.setString(1, no);
            stmt.setString(2, kp);
            stmt.setString(3, nk);
            stmt.setString(4, tgla);
            stmt.setString(5,tglb);
            stmt.setString(6, nr);
            stmt.setInt(7, status);
            int executeUpdate = stmt.executeUpdate();
            
            String sql1 = "INSERT INTO customer (nama_customer) VALUES "
                    + "('" + no +"');";
            PreparedStatement stmt1 = conn.prepareStatement("INSERT INTO customer (nama_customer) VALUES (?)");
            stmt1.setString(1, np);
            stmt1.executeUpdate();
            
        } catch (java.sql.SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan " + ex);
            return;
        }
        JOptionPane.showMessageDialog(null, "Berhasil Disimpan");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahReservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.toedter.calendar.JDateChooser tglCin;
    private com.toedter.calendar.JDateChooser tglCout;
    private javax.swing.JTextField txtKp;
    private javax.swing.JTextField txtNkamar;
    private javax.swing.JTextField txtNo;
    private javax.swing.JTextField txtNp;
    private javax.swing.JTextField txtNr;
    // End of variables declaration//GEN-END:variables
}
